AWSTemplateFormatVersion: "2010-09-09"
Description: CO-Build cluster for education

Parameters: 
  # Common paramaters
  CfnS3Bucket:
    Type: String
    Default: cloudops-dev-cfn
    Description: S3 bucket that hold cloudformation templates
  
  NamePrefix:
    Type: String
    Default: CO-Build
    Description: Name Prefix for the infastructure.

  # VPC stack parameters
  CIDRBlock01:
    Type: String
    Default: 192.168.1.0/24
    Description: VPC primary CIDR block
  
    # Public CIDR
  CIDRBlock02:
    Type: String
    Default: 195.95.1.0/24
    Description: Public CIDR block can be created from this VPC CIDR

    # POD CIDR
  CIDRBlock03:
    Type: String
    Default: 198.98.1.0/24
    Description: EKS Cluster CIDR range for VPC 

Resources: 
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        Fn::Sub: 
          - https://${CfnS3BucketName}.s3.ap-southeast-1.amazonaws.com/${CfnTemplateName}.yaml
          - CfnS3BucketName: !Ref CfnS3Bucket
            CfnTemplateName: vpc
      Parameters:
        CfnS3Bucket: !Ref CfnS3Bucket
        NamePrefix: !Ref NamePrefix
        CIDRBlock01: !Ref CIDRBlock01
        CIDRBlock02: !Ref CIDRBlock02
        CIDRBlock03: !Ref CIDRBlock03

  # To build EC2 for manage EKS cluster
  # Ec2Stack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: 
  #       Fn::Sub:
  #         - https://${CfnS3BucketName}.s3.ap-southeast-1.amazonaws.com/${CfnTemplateName}.yaml
  #         - CfnS3BucketName: !Ref CfnS3Bucket
  #           CfnTemplateName: ec2
  # # Runtime vaiables and Parameters 
  #     Parameters:
  #       VpcId: !GetAtt VpcStack.Outputs.VpcId
  #       NamePrefix: !Ref NamePrefix
  #       Ec2SubnetIds: !GetAtt VpcStack.Outputs.UtilitySubnetIds
  #       Ec2SubnetAzs: !GetAtt VpcStack.Outputs.UtilityELBSubnetAzs

  # EksStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: 
  #       Fn::Sub:
  #         - https://${CfnS3BucketName}.s3.ap-southeast-1.amazonaws.com/${CfnTemplateName}.yaml
  #         - CfnS3BucketName: !Ref CfnS3Bucket
  #           CfnTemplateName: eks
  # #### > Need to identify the runtime vaiables and update below Parameters < ####
  #     Parameters:
  #       CfnS3Bucket: !Ref CfnS3Bucket
  #       VpcId: !GetAtt VpcStack.Outputs.VpcId
  #       NamePrefix: !Ref NamePrefix
  #       NodeGroupSubnetIds: !GetAtt VpcStack.Outputs.NodeGroupSubnetIds
  #       NodeGroupSubnetAzs: !GetAtt VpcStack.Outputs.NodeGroupSubnetAzs
  #       ControlPlaneSubnetIds: !GetAtt VpcStack.Outputs.ControlPlaneSubnetIds
  #       ControlPlaneSubnetAzs: !GetAtt VpcStack.Outputs.ControlPlaneSubnetAzs
  #       PodSubnetIds: !GetAtt VpcStack.Outputs.PodSubnetIds
  #       PodSubnetAzs: !GetAtt VpcStack.Outputs.PodSubnetAzs
  #       BastionHostSecurityGroupId: !GetAtt Ec2Stack.Outputs.BastionHostSecurityGroupId
        
        
        
        
        
        
        

          
